/* index.c generated by valac 0.48.6, the Vala compiler
 * generated from index.vala, do not modify */

#include <stdlib.h>
#include <string.h>
#include <glib.h>

#define INDEX_UI "\n" \
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" \
"<!-- Generated with glade 3.40.0 -->\n" \
"<interface>\n" \
"  <requires lib=\"gtk+\" version=\"3.24\"/>\n" \
"  <object class=\"GtkAdjustment\" id=\"speed\">\n" \
"    <property name=\"lower\">1</property>\n" \
"    <property name=\"upper\">6</property>\n" \
"    <property name=\"value\">2</property>\n" \
"    <property name=\"step-increment\">1</property>\n" \
"    <property name=\"page-increment\">10</property>\n" \
"  </object>\n" \
"  <object class=\"GtkAdjustment\" id=\"zoom\">\n" \
"    <property name=\"lower\">1</property>\n" \
"    <property name=\"upper\">6</property>\n" \
"    <property name=\"value\">4</property>\n" \
"    <property name=\"step-increment\">1</property>\n" \
"    <property name=\"page-increment\">10</property>\n" \
"  </object>\n" \
"  <object class=\"GtkWindow\" id=\"window\">\n" \
"    <property name=\"visible\">True</property>\n" \
"    <property name=\"can-focus\">False</property>\n" \
"    <property name=\"default-width\">800</property>\n" \
"    <property name=\"default-height\">450</property>\n" \
"    <signal name=\"destroy\" handler=\"kick\" swapped=\"no\"/>\n" \
"    <child>\n" \
"      <object class=\"GtkBox\">\n" \
"        <property name=\"visible\">True</property>\n" \
"        <property name=\"can-focus\">False</property>\n" \
"        <child>\n" \
"          <object class=\"GtkBox\">\n" \
"            <property name=\"visible\">True</property>\n" \
"            <property name=\"can-focus\">False</property>\n" \
"            <property name=\"margin-start\">5</property>\n" \
"            <property name=\"margin-end\">5</property>\n" \
"            <property name=\"margin-top\">5</property>\n" \
"            <property name=\"margin-bottom\">5</property>\n" \
"            <property name=\"orientation\">vertical</property>\n" \
"            <child>\n" \
"              <object class=\"GtkButton\">\n" \
"                <property name=\"label\" translatable=\"yes\">Replay</" \
"property>\n" \
"                <property name=\"visible\">True</property>\n" \
"                <property name=\"can-focus\">True</property>\n" \
"                <property name=\"receives-default\">True</property>\n" \
"                <property name=\"margin-bottom\">5</property>\n" \
"                <signal name=\"clicked\" handler=\"ft_replay\" swapped" \
"=\"no\"/>\n" \
"              </object>\n" \
"              <packing>\n" \
"                <property name=\"expand\">False</property>\n" \
"                <property name=\"fill\">True</property>\n" \
"                <property name=\"position\">0</property>\n" \
"              </packing>\n" \
"            </child>\n" \
"            <child>\n" \
"              <object class=\"GtkLabel\">\n" \
"                <property name=\"visible\">True</property>\n" \
"                <property name=\"can-focus\">False</property>\n" \
"                <property name=\"margin-bottom\">4</property>\n" \
"                <property name=\"label\" translatable=\"yes\">ZOOM</pr" \
"operty>\n" \
"              </object>\n" \
"              <packing>\n" \
"                <property name=\"expand\">False</property>\n" \
"                <property name=\"fill\">True</property>\n" \
"                <property name=\"position\">1</property>\n" \
"              </packing>\n" \
"            </child>\n" \
"            <child>\n" \
"              <object class=\"GtkSpinButton\">\n" \
"                <property name=\"visible\">True</property>\n" \
"                <property name=\"can-focus\">True</property>\n" \
"                <property name=\"adjustment\">zoom</property>\n" \
"                <signal name=\"value-changed\" handler=\"ft_zoom\" obj" \
"ect=\"zoom\" swapped=\"no\"/>\n" \
"              </object>\n" \
"              <packing>\n" \
"                <property name=\"expand\">False</property>\n" \
"                <property name=\"fill\">True</property>\n" \
"                <property name=\"position\">2</property>\n" \
"              </packing>\n" \
"            </child>\n" \
"            <child>\n" \
"              <object class=\"GtkLabel\">\n" \
"                <property name=\"visible\">True</property>\n" \
"                <property name=\"can-focus\">False</property>\n" \
"                <property name=\"margin-bottom\">4</property>\n" \
"                <property name=\"label\" translatable=\"yes\">SPEED</p" \
"roperty>\n" \
"              </object>\n" \
"              <packing>\n" \
"                <property name=\"expand\">False</property>\n" \
"                <property name=\"fill\">True</property>\n" \
"                <property name=\"position\">3</property>\n" \
"              </packing>\n" \
"            </child>\n" \
"            <child>\n" \
"              <object class=\"GtkSpinButton\">\n" \
"                <property name=\"visible\">True</property>\n" \
"                <property name=\"can-focus\">True</property>\n" \
"                <property name=\"progress-pulse-step\">0</property>\n" \
"                <property name=\"adjustment\">speed</property>\n" \
"                <signal name=\"value-changed\" handler=\"ft_speed\" ob" \
"ject=\"speed\" swapped=\"no\"/>\n" \
"              </object>\n" \
"              <packing>\n" \
"                <property name=\"expand\">False</property>\n" \
"                <property name=\"fill\">True</property>\n" \
"                <property name=\"position\">4</property>\n" \
"              </packing>\n" \
"            </child>\n" \
"            <child>\n" \
"              <object class=\"GtkButton\">\n" \
"                <property name=\"label\" translatable=\"yes\">Nouveau<" \
"/property>\n" \
"                <property name=\"visible\">True</property>\n" \
"                <property name=\"can-focus\">True</property>\n" \
"                <property name=\"receives-default\">True</property>\n" \
"                <property name=\"margin-top\">40</property>\n" \
"                <property name=\"margin-bottom\">4</property>\n" \
"                <signal name=\"clicked\" handler=\"ft_nouveau\" swappe" \
"d=\"no\"/>\n" \
"              </object>\n" \
"              <packing>\n" \
"                <property name=\"expand\">False</property>\n" \
"                <property name=\"fill\">True</property>\n" \
"                <property name=\"position\">5</property>\n" \
"              </packing>\n" \
"            </child>\n" \
"            <child>\n" \
"              <object class=\"GtkBox\">\n" \
"                <property name=\"visible\">True</property>\n" \
"                <property name=\"can-focus\">False</property>\n" \
"                <child>\n" \
"                  <object class=\"GtkLabel\">\n" \
"                    <property name=\"visible\">True</property>\n" \
"                    <property name=\"can-focus\">False</property>\n" \
"                    <property name=\"label\" translatable=\"yes\">Nomb" \
"re de coup:</property>\n" \
"                  </object>\n" \
"                  <packing>\n" \
"                    <property name=\"expand\">False</property>\n" \
"                    <property name=\"fill\">True</property>\n" \
"                    <property name=\"position\">0</property>\n" \
"                  </packing>\n" \
"                </child>\n" \
"                <child>\n" \
"                  <object class=\"GtkLabel\" id=\"nbr_coup\">\n" \
"                    <property name=\"visible\">True</property>\n" \
"                    <property name=\"can-focus\">False</property>\n" \
"                    <property name=\"label\" translatable=\"yes\">0</p" \
"roperty>\n" \
"                  </object>\n" \
"                  <packing>\n" \
"                    <property name=\"expand\">False</property>\n" \
"                    <property name=\"fill\">True</property>\n" \
"                    <property name=\"position\">1</property>\n" \
"                  </packing>\n" \
"                </child>\n" \
"              </object>\n" \
"              <packing>\n" \
"                <property name=\"expand\">False</property>\n" \
"                <property name=\"fill\">True</property>\n" \
"                <property name=\"position\">6</property>\n" \
"              </packing>\n" \
"            </child>\n" \
"            <child>\n" \
"              <object class=\"GtkToggleButton\">\n" \
"                <property name=\"label\" translatable=\"yes\">Pause</p" \
"roperty>\n" \
"                <property name=\"visible\">True</property>\n" \
"                <property name=\"can-focus\">True</property>\n" \
"                <property name=\"receives-default\">True</property>\n" \
"                <property name=\"margin-top\">5</property>\n" \
"                <signal name=\"toggled\" handler=\"ft_pause\" swapped=" \
"\"no\"/>\n" \
"              </object>\n" \
"              <packing>\n" \
"                <property name=\"expand\">False</property>\n" \
"                <property name=\"fill\">True</property>\n" \
"                <property name=\"position\">7</property>\n" \
"              </packing>\n" \
"            </child>\n" \
"          </object>\n" \
"          <packing>\n" \
"            <property name=\"expand\">False</property>\n" \
"            <property name=\"fill\">True</property>\n" \
"            <property name=\"position\">0</property>\n" \
"          </packing>\n" \
"        </child>\n" \
"        <child>\n" \
"          <object class=\"GtkScrolledWindow\">\n" \
"            <property name=\"visible\">True</property>\n" \
"            <property name=\"can-focus\">True</property>\n" \
"            <property name=\"shadow-type\">in</property>\n" \
"            <child>\n" \
"              <object class=\"GtkViewport\">\n" \
"                <property name=\"visible\">True</property>\n" \
"                <property name=\"can-focus\">False</property>\n" \
"                <child>\n" \
"                  <object class=\"GtkDrawingArea\" id=\"drawing_a\">\n" \
"                    <property name=\"visible\">True</property>\n" \
"                    <property name=\"can-focus\">False</property>\n" \
"                  </object>\n" \
"                </child>\n" \
"              </object>\n" \
"            </child>\n" \
"          </object>\n" \
"          <packing>\n" \
"            <property name=\"expand\">True</property>\n" \
"            <property name=\"fill\">True</property>\n" \
"            <property name=\"position\">1</property>\n" \
"          </packing>\n" \
"        </child>\n" \
"        <child>\n" \
"          <object class=\"GtkScrolledWindow\">\n" \
"            <property name=\"visible\">True</property>\n" \
"            <property name=\"can-focus\">True</property>\n" \
"            <property name=\"shadow-type\">in</property>\n" \
"            <child>\n" \
"              <object class=\"GtkViewport\">\n" \
"                <property name=\"visible\">True</property>\n" \
"                <property name=\"can-focus\">False</property>\n" \
"                <child>\n" \
"                  <object class=\"GtkDrawingArea\" id=\"drawing_b\">\n" \
"                    <property name=\"visible\">True</property>\n" \
"                    <property name=\"can-focus\">False</property>\n" \
"                  </object>\n" \
"                </child>\n" \
"              </object>\n" \
"            </child>\n" \
"          </object>\n" \
"          <packing>\n" \
"            <property name=\"expand\">True</property>\n" \
"            <property name=\"fill\">True</property>\n" \
"            <property name=\"position\">2</property>\n" \
"          </packing>\n" \
"        </child>\n" \
"      </object>\n" \
"    </child>\n" \
"  </object>\n" \
"</interface>\n"

